let miNumero = 123;
let miNumero2 = 12.3;
let miString = "argentina";
let miBoolean = true;
let indefinido;
let miObjeto1 = {} ;
console.log ("Numero: "+ miNumero + typeof miNumero);
console.log ("Numero2: "+ miNumero2 + typeof miNumero2);
console.log ("String: "+ miString + typeof miString);
console.log ("Boolean: " + miBoolean + typeof miBoolean);
console.log ("Indefinido: "+ indefinido +typeof indefinido);
console.log ("Objeto: "+ miObjeto1 +typeof miObjeto1);